imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: twig_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: { fallbacks: [en] }


mobile_detect:
    redirect:
        mobile:
            is_enabled: true
            #host: http://m.example.com
            #action: redirect
        detect_tablet_as_mobile: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #exception_controller:  AppBundle:Exception:showException
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "bootstrap_3_horizontal_layout.html.twig"
        #- "TbbcMoneyBundle:Form:fields.html.twig"
        # user are own for bootstrap
        - "form/tbbc_money.html.twig"
        - "form/textarea_prepend.html.twig"
        - "form/date_picker.html.twig"
        - "form/date_time_picker.html.twig"
        - "form/collection.html.twig"
        - "form/compound.html.twig"
    paths:
      - "%kernel.root_dir%/Resources/views/layout/bootstrap"

    globals:
        global:
          site:
            {name: "%site_name%", version: "%site_version%"}
          support:
            {email: "%support_email%"}
          meta:
            {description: "sarasoft", author: "Ricardo Saracino", application_name: "sarasoft"}


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            datetime: AppBundle\Doctrine\DBAL\Type\UTCDateTimeType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            money: Tbbc\MoneyBundle\Type\MoneyType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

tbbc_money:
    currencies: ["CAD"]
    reference_currency: "CAD"
    decimals: 2

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js"
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css"
            filters: [cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
            output: "fonts/glyphicons-halflings-regular.woff"
        jquery_and_ui:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.js"

