security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

        Symfony\Component\Security\Core\User\User: plaintext


    providers:
        chain_providers:
            chain:
                providers: [main, in_memory]

        main:
            entity:
                class: AppBundle:User

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: chain_providers
            form_login:
              login_path: /login
              check_path: /login
              always_use_default_target_path: false
              default_target_path: /
              # form params defined in LoginType.php and SecurityController.php
              username_parameter: login[username]
              password_parameter: login[password]

            logout:
               path:                 /logout
               target:               /
               #success_handler:      ~
               invalidate_session:   true
               delete_cookies:
                   name:
                       path:                 null
                       domain:               null


    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        # make sure ROLE_SUPER_ADMIN has all roles for RoleHelper::getAllUserRoles
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
