security:

    encoders:
        AppBundle\Entity\User: plaintext

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
              login_path: /login
              check_path: /login
              always_use_default_target_path: false
              default_target_path: /welcome

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/welcome, roles: ROLE_USER }

