# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app_bundle.service.listener:
        class: AppBundle\Listener\CustomerOrderCalendarListener
        arguments: ["@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }

    app_bundle.type.hidden_entity:
        class: AppBundle\Form\Type\HiddenEntityType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type, alias: hidden_entity }

    app_bundle.type.user_date_time_picker:
        class: AppBundle\Form\Type\UserDateTimePickerType
        arguments: ["@security.token_storage"]
        tags:
          - { name: form.type, alias: user_date_time_picker }


    app_bundle.type.user_text_area_type:
        class: AppBundle\Form\Type\UserTextAreaType
        arguments: ["@security.token_storage"]
        tags:
          - { name: form.type, alias: user_text_area_type }



    app_bundle.type.user_text_area_prepend_type:
        class: AppBundle\Form\Type\UserTextAreaPrependType
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
          - { name: form.type, alias: user_text_area_prepend_type }
