# services to handle doctrine extensions
# import it in config.yml
services:
  twig.user_date_extension:
      class: AppBundle\Twig\UserDateExtension
      tags:
          - { name: twig.extension }
      arguments:
          - "@security.token_storage"