# services to handle doctrine extensions
# import it in config.yml
services:
  twig.user_date_extension:
      class: AppBundle\Twig\UserDateExtension
      tags:
          - { name: twig.extension }
      arguments:
          - "@security.token_storage"

  twig.user_money_extension:
      class: AppBundle\Twig\UserMoneyExtension
      tags:
          - { name: twig.extension }
      arguments:
          - "@security.token_storage"

  twig.country_extension:
      class: AppBundle\Twig\CountryExtension
      tags:
          - { name: twig.extension }

  twig.language_extension:
      class: AppBundle\Twig\LanguageExtension
      tags:
          - { name: twig.extension }

  twig.AdministrativeArea_extension:
      class: AppBundle\Twig\AdministrativeAreaExtension
      tags:
          - { name: twig.extension }

  twig.customerOrderRouting_extension:
      class: AppBundle\Twig\CustomerOrderRoutingExtension
      tags:
          - { name: twig.extension }
      arguments:
          - "@router"