# services to handle doctrine extensions
# import it in config.yml
services:
  twig.user_date_extension:
      class: AppBundle\Twig\UserDateExtension
      arguments:
          - "@security.token_storage"
      tags:
          - { name: twig.extension }

  twig.user_money_extension:
      class: AppBundle\Twig\UserMoneyExtension
      arguments:
          - "@security.token_storage"
      tags:
          - { name: twig.extension }

  twig.address_extension:
      class: AppBundle\Twig\AddressExtension
      tags:
          - { name: twig.extension }

  twig.language_extension:
      class: AppBundle\Twig\LanguageExtension
      tags:
          - { name: twig.extension }

  twig.customerOrderRouting_extension:
      class: AppBundle\Twig\CustomerOrderRoutingExtension
      arguments:
          - "@router"
      tags:
          - { name: twig.extension }

  twig.customerOrderEntityManager_extension:
      class: AppBundle\Twig\CustomerOrderEntityManagerExtension
      arguments:
          - "@doctrine.orm.entity_manager"
      tags:
          - { name: twig.extension }